apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nublado.fullname" . }}-js9
  labels:
    name: {{ template "nublado.fullname" . }}-js9
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "nublado.fullname" . }}-js9
  template:
    metadata:
      labels:
        name: {{ template "nublado.fullname" . }}-js9
    spec:
      containers:
        - name: {{ template "nublado.fullname" . }}-js9
          imagePullPolicy: "Always"
          image: {{ .Values.js9.image }}
          resources:
            limits:
              memory: 4G
              cpu: 2.0
            requests:
              memory: 1G
              cpu: 0.5
          ports:
            - containerPort: 80
              name: web
            - containerPort: 2718
              name: e
          env:
            - name: FQDN
              value: '{{.Values.fqdn}}'
            - name: HELM_TAG
              value: '{{ template "nublado.fullname" . }}'
            # Set to non-empty value to enable debugging.
            - name: DEBUG
              value: '{{.Values.debug}}'
            - name: JS9_ROUTE
              value: '{{.Values.routes.js9}}'
            - name: EXTERNAL_JS9_URL
              value: '{{.Values.routes.external.js9}}'
          volumeMounts:
            - name: metadata
              mountPath: /etc/metadata
              readOnly: false
      {{- if .Values.pull_secret }}
      imagePullSecrets:
      - name: {{ .Values.pull_secret }}
      {{- end }}
      volumes:
        - name: metadata
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
