# -- Version of the Strimzi Custom Resource API. The correct value depends on
# the deployed version of Strimzi. See [this blog
# post](https://strimzi.io/blog/2021/04/29/api-conversion/) for more.
strimziAPIVersion: v1beta2

cluster:
  # -- Name used for the Kafka broker, and used by Strimzi for many annotations.
  name: alert-broker

kafka:
  # -- Version of Kafka to deploy.
  version: 2.8.1
  # -- Encoding version for messages, see
  # https://strimzi.io/docs/operators/latest/deploying.html#ref-kafka-versions-str.
  logMessageFormatVersion: 2.8
  # -- Version of the protocol for inter-broker communication, see
  # https://strimzi.io/docs/operators/latest/deploying.html#ref-kafka-versions-str.
  interBrokerProtocolVersion: 2.8

  # -- Number of Kafka broker replicas to run.
  replicas: 3

  # -- Size of the backing storage disk for the Kafka brokers.
  storage: 300Gi

# -- A list of usernames for users who should have global admin permissions.
# These users will be created, along with their credentials.
superusers:
  - kafka-admin

zookeeper:
  # -- Number of Zookeeper replicas to run.
  replicas: 3
  # -- Size of the backing storage disk for the Zookeeper instances.
  storage: 50Gi
