apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cadc-tap.fullname" . }}-tap-schema-db
  labels:
    app: {{ template "cadc-tap.fullname" . }}-tap-schema-db
{{ include "cadc-tap.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cadc-tap.fullname" . }}-tap-schema-db
  template:
    metadata:
      labels:
        app: {{ template "cadc-tap.fullname" . }}-tap-schema-db
{{ include "cadc-tap.labels" . | indent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ template "cadc-tap.fullname" . }}-tap-schema-db
        env:
        - name: MYSQL_DATABASE
          value: "TAP_SCHEMA"
        - name: MYSQL_USER
          value: "TAP_SCHEMA"
        - name: MYSQL_PASSWORD
          value: "TAP_SCHEMA"
        - name: MYSQL_ROOT_HOST
          value: "%"
        image: lsstdax/tap-schema-db:{{ .Values.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        resources:
          {{toYaml .Values.aux_resources | nindent 10}}
