apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helpers.fullname" . }}
  labels:
    app: {{ template "helpers.fullname" . }}
{{ include "helpers.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "helpers.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "helpers.fullname" . }}
{{ include "helpers.labels" . | indent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gafaelfawr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 8080
              name: app
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: {{ template "helpers.fullname" . }}-config
              mountPath: "/etc/gafaelfawr"
              readOnly: true
            - name: {{ template "helpers.fullname" . }}-secret
              mountPath: "/etc/gafaelfawr/secrets"
              readOnly: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
        - name: {{ template "helpers.fullname" . }}-config
          configMap:
            name: {{ template "helpers.fullname" . }}-configmap
        - name: {{ template "helpers.fullname" . }}-secret
          secret:
            secretName: {{ template "helpers.fullname" . }}-secret
