imagePullSecrets:
  - "pull-secret"
ingress:
  host: "lsst-lsp-stable.ncsa.illinois.edu"
  externalAuthUrl: true
vaultSecretsPath: "secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/gafaelfawr"

# Use an existing, manually-managed PVC for Redis.
redis:
  persistence:
    volumeClaimName: "auth-redis-volume-claim"

config:
  host: "lsst-lsp-stable.ncsa.illinois.edu"

  # IP range used by the cluster, used to determine the true client IP for
  # logging.
  proxies:
    - "41.142.182.128/26"

  # Use CILogon authentication.
  cilogon:
    clientId: "cilogon:/client_id/7ae419868b97e81644ced9886ffbcec"
    redirectUrl: "https://lsst-lsp-stable.ncsa.illinois.edu/oauth2/callback"
    loginParams:
      skin: "LSST"

  # Use NCSA groups to determine token scopes.
  groupMapping:
    "exec:admin": ["lsst_int_lsp_admin"]
    "exec:notebook": ["lsst_int_lspdev"]
    "exec:portal": ["lsst_int_lspdev"]
    "exec:user": ["lsst_int_lspdev"]
    "read:tap": ["lsst_int_lspdev"]
