apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: "TCP"
      targetPort: 6379
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
