apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "firefly.fullname" . }}
  labels:
{{ include "firefly.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/proxy-body-size: "0m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "24k"
    nginx.ingress.kubernetes.io/client-header-buffer-size: "24k"
    nginx.ingress.kubernetes.io/rewrite-target: /suit$1$2
    nginx.ingress.kubernetes.io/proxy-redirect-from: /suit/
    nginx.ingress.kubernetes.io/proxy-redirect-to: /portal/app/
    nginx.ingress.kubernetes.io/proxy-cookie-path: /suit /portal/app
    nginx.ingress.kubernetes.io/session-cookie-path: /portal/app
{{ if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{ end }}
spec:
  rules:
{{ if .Values.ingress.host }}
  - host: {{ .Values.ingress.host }}
    http:
{{ else }}
  - http:
{{ end }}
      paths:
      - path: "/portal/app(/|$)(.*)"
        backend:
          serviceName: {{ include "firefly.fullname" . }}
          servicePort: 8080
