apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-registry-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: strimzi-registry-operator
  template:
    metadata:
      labels:
        app: strimzi-registry-operator
    spec:
      serviceAccountName: strimzi-registry-operator
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          env:
          - name: SSR_CLUSTER_NAME
            value: {{ required "A valid .Values.clusterName entry required" .Values.clusterName | quote }}
          - name: SSR_NAMESPACE
            value: {{ .Values.clusterNamespace | quote }}
          command: ["kopf"]
          args: ["run",  "--standalone",  "-m",  "strimziregistryoperator.handlers",  "--namespace",  "{{ .Values.clusterNamespace }}",  "--verbose"]
