apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    k8s-app:  {{ template "helpers.fullname" . }}-jwt-authorizer
  name:  {{ template "helpers.fullname" . }}-jwt-authorizer
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: {{ template "helpers.fullname" . }}-jwt-authorizer
  sessionAffinity: None
  type: ClusterIP
