{{ if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helpers.fullname" . }}-jwt-authorizer-secret
type: Opaque
stringData:
  oauth2_proxy_client_secret.txt: |-
    {{ .Values.secrets.oauth2_proxy_client_secret }}
  oauth2_proxy_cookie_secret.txt: |-
    {{ .Values.secrets.oauth2_proxy_cookie_secret }}
  flask_secret.txt: |-
    {{ .Values.secrets.flask_secret }}
  signing_key.pem: |-
{{ .Values.secrets.signing_key | indent 4 }}
{{ end }}
