apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jwt-authorizer
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /auth
