apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helpers.fullname" . }}-jwt-authorizer
  labels:
    k8s-app: {{ template "helpers.fullname" . }}-jwt-authorizer
{{ include "helpers.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ template "helpers.fullname" . }}-jwt-authorizer
  template:
    metadata:
      labels:
        k8s-app: {{ template "helpers.fullname" . }}-jwt-authorizer
{{ include "helpers.labels" . | indent 8 }}
    spec:
      containers:
      - image:  "{{ .Values.jwt_authorizer.image | default "lsstdm/jwt_authorizer:stable" }}"
        imagePullPolicy: Always
        name: jwt-authorizer
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: jwt-authorizer-config
          mountPath: "/etc/jwt-authorizer"
          readOnly: true
        - name: jwt-authorizer-secret
          mountPath: "/etc/jwt-authorizer/secrets"
          readOnly: true
      volumes:
      - name: jwt-authorizer-config
        configMap:
          name: {{ template "helpers.fullname" . }}-jwt-authorizer-config
      - name: jwt-authorizer-secret
        secret:
          secretName: {{ template "helpers.fullname" . }}-jwt-authorizer-secret
