apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    k8s-app: {{ template "helpers.fullname" . }}-oauth2-proxy
  name: {{ template "helpers.fullname" . }}-oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: {{ template "helpers.fullname" . }}-oauth2-proxy
  sessionAffinity: None
  type: ClusterIP
