apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: Always
        args:
        - redis-server
        - --appendonly yes
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "1"
        volumeMounts:
        - name: redis-data
          mountPath: "/data"
      volumes:
      - name: redis-data
        emptyDir: {}
