apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: well-known-jwks
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: well-known-jwks
          servicePort: 80
        path: /.well-known/jwks.json
