apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "helpers.fullname" . }}-jwt-authorizer
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "helpers.fullname" . }}-oauth2-proxy
          servicePort: 4180
        path: /auth
