{{ if .Values.vault_secrets.enabled }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ template "helpers.fullname" . }}-jwt-authorizer-secret
spec:
  path: {{ .Values.vault_secrets.path }}
  type: Opaque
{{ end }}
