{{- if .Values.influxdbSink.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-connect-manager.name" . }}
  labels:
    helm.sh/chart: {{ include "kafka-connect-manager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kafka-connect-manager.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "kafka-connect-manager.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name:  {{ include "kafka-connect-manager.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy:  {{ .Values.image.pullPolicy }}
        command:
        - kafkaconnect
        - create
        - influxdb-sink
        {{- if .Values.influxdbSink.autoUpdate }}
        - --auto-update
        {{- end }}
        env:
          - name: KAFKA_CONNECT_NAME
            value: {{ .Values.influxdbSink.name | quote }}
          - name: KAFKA_CONNECT_INFLUXDB_URL
            value: {{ .Values.influxdbSink.connectInfluxUrl | quote }}
          - name: KAFKA_CONNECT_DATABASE
            value: {{ .Values.influxdbSink.connectInfluxDb | quote }}
          - name: KAFKA_CONNECT_INFLUXDB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.influxdbSink.influxSecret | quote }}
                key: influxdb-user
          - name: KAFKA_CONNECT_INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.influxdbSink.influxSecret | quote }}
                key: influxdb-password
          - name: KAFKA_CONNECT_TASKS_MAX
            value: {{ .Values.influxdbSink.tasksMax | quote }}
          - name: KAFKA_CONNECT_TOPIC_REGEX
            value: {{ .Values.influxdbSink.topicRegex | quote }}
          - name: KAFKA_CONNECT_CHECK_INTERVAL
            value: {{ .Values.influxdbSink.checkInterval | quote  }}
          - name: KAFKA_CONNECT_EXCLUDED_TOPICS
            value: {{ .Values.influxdbSink.excludedTopics | quote }}
          - name: KAFKA_CONNECT_INFLUXDB_TIMESTAMP
            value: {{ .Values.influxdbSink.timestamp | quote }}
          - name: KAFKA_CONNECT_ERROR_POLICY
            value: {{ .Values.influxdbSink.connectInfluxErrorPolicy | quote }}
          - name: KAFKA_CONNECT_MAX_RETRIES
            value: {{ .Values.influxdbSink.connectInfluxMaxRetries | quote }}
          - name: KAFKA_CONNECT_RETRY_INTERVAL
            value: {{ .Values.influxdbSink.connectInfluxRetryInterval | quote }}
          - name: KAFKA_CONNECT_PROGRESS_ENABLED
            value: {{ .Values.influxdbSink.connectProgressEnabled | quote }}
          - name: KAFKA_BROKER_URL
            value: {{ .Values.env.kafkaBrokerUrl | quote }}
          - name: KAFKA_CONNECT_URL
            value: {{ .Values.env.kafkaConnectUrl | quote }}
{{- end }}
