{{- range .Values.influxdbSink }}
{{- with . }}
{{- if .enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ printf "%s" $.Chart.Name | trunc 63 | trimSuffix "-" }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ printf "%s" $.Chart.Name | trunc 63 | trimSuffix "-" }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      containers:
      - name:  "kafka-connect-manager"
        image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
        imagePullPolicy:  {{ $.Values.image.pullPolicy }}
        command:
        - kafkaconnect
        - create
        - influxdb-sink
        {{- if .autoUpdate }}
        - --auto-update
        {{- end }}
        env:
          - name: KAFKA_CONNECT_NAME
            value: {{ .name | quote }}
          - name: KAFKA_CONNECT_INFLUXDB_URL
            value: {{ .connectInfluxUrl | quote }}
          - name: KAFKA_CONNECT_DATABASE
            value: {{ .connectInfluxDb | quote }}
          - name: KAFKA_CONNECT_INFLUXDB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .influxSecret | quote }}
                key: influxdb-user
          - name: KAFKA_CONNECT_INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .influxSecret | quote }}
                key: influxdb-password
          - name: KAFKA_CONNECT_TASKS_MAX
            value: {{ .tasksMax | quote }}
          - name: KAFKA_CONNECT_TOPIC_REGEX
            value: {{ .topicRegex | quote }}
          - name: KAFKA_CONNECT_CHECK_INTERVAL
            value: {{ .checkInterval | quote  }}
          - name: KAFKA_CONNECT_EXCLUDED_TOPIC_REGEX
            value: {{ .excludedTopicRegex | quote }}
          - name: KAFKA_CONNECT_INFLUXDB_TIMESTAMP
            value: {{ .timestamp | quote }}
          - name: KAFKA_CONNECT_ERROR_POLICY
            value: {{ .connectInfluxErrorPolicy | quote }}
          - name: KAFKA_CONNECT_MAX_RETRIES
            value: {{ .connectInfluxMaxRetries | quote }}
          - name: KAFKA_CONNECT_RETRY_INTERVAL
            value: {{ .connectInfluxRetryInterval | quote }}
          - name: KAFKA_CONNECT_PROGRESS_ENABLED
            value: {{ .connectProgressEnabled | quote }}
          - name: KAFKA_BROKER_URL
            value: {{ $.Values.env.kafkaBrokerUrl | quote }}
          - name: KAFKA_CONNECT_URL
            value: {{ $.Values.env.kafkaConnectUrl | quote }}
{{- end }}
{{- end }}
{{- end }}
