apiVersion: batch/v1
kind: Job
metadata:
  name: fs-provisioner
spec:
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: fs-provisioner
          volumeMounts:
          - mountPath: /storage
            name: storage
      restartPolicy: Never
      volumes:
      - name: storage
        nfs:
          server: {{ .Values.nfs.host }}
          path: {{ .Values.nfs.path }}
